class CountryCodes {
  Map<String, String> countryCodes = {
    'Argentina': 'ar',
    'Austria': 'at',
    'Australia': 'au',
    'Belgium': 'be',
    'Bulgaria': 'bg',
    'Bolivia': 'bo',
    'Brazil': 'br',
    'Canada': 'ca',
    'Chile': 'cl',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Estonia': 'ee',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Guatemala': 'gt',
    'Hong Kong': 'hk',
    'Honduras': 'hn',
    'Hungary': 'hu',
    'Indonesia': 'id',
    'Ireland': 'ie',
    'Israel': 'il',
    'India': 'in',
    'Iceland': 'is',
    'Italy': 'it',
    'Japan': 'jp',
    'Korea': 'kr',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Latvia': 'lv',
    'Morocco': 'ma',
    'Mexico': 'mx',
    'Malaysia': 'my',
    'Nicaragua': 'ni',
    'Netherlands': 'nl',
    'Norway': 'no',
    'New Zealand': 'nz',
    'Panama': 'pa',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Paraguay': 'py',
    'Romania': 'ro',
    'Russian Federation': 'ru',
    'Saudi Arabia': 'sa',
    'Sweden': 'se',
    'Singapore': 'sg',
    'Spain': 'es',
    'South Africa': 'za',
    'Slovakia': 'sk',
    'Switzerland': 'ch',
    'Thailand': 'th',
    'Turkey': 'tr',
    'Taiwan': 'tw',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Uruguay': 'uy',
    'Vietnam': 'vn'
  };
}
